language: node_js
node_js:
- '7'
cache: yarn
deploy:
  provider: npm
  email: bano.notit@gmail.com
  api_key:
    secure: r4EWC01+28tAP2RCImpdKsK3FwJaStA90kR2zZmcJ/XkMo9RmVJBv1lpf8rsvnpYgi6xMnmQrclr1TfnQBNqiUa1L/W99GwN8VOjX7lnL0G9LwK2CpebCl0vrWKqH3DT4v2WwhEodsdXwCONw1iIQpavfYgfPutDsG9Nnz5Z4VZ0ku3XP9kKTznYzj9rcF1QjMBzCEa6AKMRzoCCYeTud5owMyeuCJF3oBa8QztrQ0KJ96GIPr/wSVDCFE4pVYJDqJt3PjuqqMIA5PXX9+YrQrI7YvMTSYTkWjleA6CzIaisQDS7ueHPk9b3+QGWVZfiH4+obOHsXZBhq+s5SWzZJ/eS8F7uwO1pWocUUK9bP7hXF1jUXkJ7Blez4zD1JwhalF7HEUjeGsh2PDdbYcZZnOY4vTJSI3LRx5VFMOw2sjOgnWplyeH0icti0rMyTIox8l8zBxX3KH111ze4bm5DYF9irj+GebV4urbw3mtxeDV8C1faJUGVuCabcO4+5Xt9zE8s0p80bRKkg061v5PNcMhYvfoio3v07o1r3B8FDPoDaJ9v2lHdOqUpPvmB9lD0aagnRXWNuiLamF8v8M7a6j/kx2eWKU2mzup0GutvZF703iCcGcS8Im+yxodtlLno4laQUUvFdzfwUHluzPl7jgpWDtf1IHDpo0EcP4AHf9k=
  on:
    tags: true
    repo: BANOnotIT/react-fontello
    all_branches: true
